// src/components/canvas/utils/componentLibrary.js
export const COMPONENT_CATEGORIES = [
  {
    id: "frontend",
    title: "Frontend",
    components: [
      {
        id: "react",
        label: "React",
        category: "frontend",
        technology: "React 19",
        icon: "⚛️",
        description: "Modern React application",
        tags: ["SPA", "REST"],
      },
      {
        id: "nextjs",
        label: "Next.js",
        category: "frontend",
        technology: "Next.js",
        icon: "▲",
        description: "React Full Stack Framework",
        tags: ["SSR", "SEO"],
      },
      {
        id: "angular",
        label: "Angular",
        category: "frontend",
        technology: "Angular",
        icon: "🅰️",
        description: "Angular Application",
        tags: ["TypeScript"],
      },
      {
        id: "vue",
        label: "Vue",
        category: "frontend",
        technology: "Vue.js",
        icon: "💚",
        description: "Vue Frontend",
        tags: [],
      },
    ],
  },
  {
    id: "backend",
    title: "Backend",
    components: [
      {
        id: "springboot",
        label: "Spring Boot",
        category: "backend",
        technology: "Spring Boot",
        icon: "🍃",
        description: "REST Backend",
        tags: ["REST", "Java"],
      },
      {
        id: "node",
        label: "Node.js",
        category: "backend",
        technology: "Express",
        icon: "🟢",
        description: "Node Backend",
        tags: ["REST"],
      },
      {
        id: "python",
        label: "Python",
        category: "backend",
        technology: "FastAPI",
        icon: "🐍",
        description: "Python API",
        tags: ["AI"],
      },
      {
        id: "dotnet",
        label: ".NET",
        category: "backend",
        technology: ".NET Core",
        icon: "💜",
        description: ".NET Backend",
        tags: [],
      },
    ],
  },
  {
    id: "database",
    title: "Database",
    components: [
      {
        id: "postgres",
        label: "PostgreSQL",
        category: "database",
        technology: "PostgreSQL",
        icon: "🐘",
        description: "Relational Database",
        tags: ["SQL"],
      },
      {
        id: "mysql",
        label: "MySQL",
        category: "database",
        technology: "MySQL",
        icon: "🐬",
        description: "Relational Database",
        tags: ["SQL"],
      },
      {
        id: "mongodb",
        label: "MongoDB",
        category: "database",
        technology: "MongoDB",
        icon: "🍃",
        description: "NoSQL Database",
        tags: ["NoSQL"],
      },
    ],
  },
  {
    id: "cache",
    title: "Cache",
    components: [
      {
        id: "redis",
        label: "Redis",
        category: "cache",
        technology: "Redis",
        icon: "⚡",
        description: "Distributed Cache",
        tags: ["Cache"],
      },
    ],
  },
  {
    id: "messaging",
    title: "Messaging",
    components: [
      {
        id: "kafka",
        label: "Kafka",
        category: "queue",
        technology: "Kafka",
        icon: "📨",
        description: "Event Streaming",
        tags: ["Async"],
      },
      {
        id: "rabbitmq",
        label: "RabbitMQ",
        category: "queue",
        technology: "RabbitMQ",
        icon: "🐇",
        description: "Message Broker",
        tags: ["Queue"],
      },
    ],
  },
  {
    id: "security",
    title: "Security",
    components: [
      {
        id: "jwt",
        label: "JWT",
        category: "security",
        technology: "JWT",
        icon: "🔐",
        description: "Authentication",
        tags: ["Security"],
      },
      {
        id: "oauth2",
        label: "OAuth2",
        category: "security",
        technology: "OAuth2",
        icon: "🛡️",
        description: "Authorization",
        tags: [],
      },
    ],
  },
  {
    id: "ai",
    title: "Artificial Intelligence",
    components: [
      {
        id: "llm",
        label: "LLM",
        category: "ai",
        technology: "GPT / Claude / Gemini",
        icon: "🤖",
        description: "Large Language Model",
        tags: ["AI"],
      },
      {
        id: "rag",
        label: "RAG",
        category: "ai",
        technology: "Retrieval",
        icon: "📚",
        description: "Retrieval Augmented Generation",
        tags: [],
      },
      {
        id: "mcp",
        label: "MCP",
        category: "ai",
        technology: "Model Context Protocol",
        icon: "🔌",
        description: "AI Tool Integration",
        tags: [],
      },
      {
        id: "agent",
        label: "AI Agent",
        category: "ai",
        technology: "LangGraph",
        icon: "🧠",
        description: "Autonomous AI Agent",
        tags: [],
      },
    ],
  },
];
